format: "yaml"
providers:
  - name: gitlab
    token: "gl***"
    base_url: "https://gitlab.com"
    lookback_hours: 96
    state: "all"
    authors:
      - bob
      - alice
    repos:
      - foo/bar
      - foo/baz
